# Generated by Django 5.2.3 on 2025-06-12 15:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='created by')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='updated by')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='deleted date')),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted by')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('type', models.CharField(choices=[('comestibles', 'Comestibles'), ('ocio', 'Ocio'), ('electronica', 'Electrónica'), ('servicio públicos', 'Servicios públicos'), ('ropa', 'Ropa'), ('salud', 'Salud'), ('otros', 'Otros')], max_length=50, verbose_name='Type')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-payment_date'],
            },
        ),
    ]
